"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useState } from "react";

import "./globals.css";
import TopBar from '@/components/TopBar';
import LeftSidebar from '@/components/LeftSidebar';
import { Typography } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

//export const metadata: Metadata = {
//  title: "Task Manager",
//  description: "Generated by create next app",
//};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);

  return (
    <html lang="en">
      <body className={inter.className} style={{ margin:0, height: '100vh', display: 'flex'}}>
        <LeftSidebar open={isSidebarOpen}/>
        <div style={{ display: 'flex', flexDirection: 'column', flexGrow: 1}}>
          <TopBar onMenuClick={() => setIsSidebarOpen(!isSidebarOpen)}/>
          <main style={{ backgroundColor: 'yellow', flexGrow: 1, justifyContent: 'center', alignItems: 'center' }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
