"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useState } from "react";

import "./globals.css";
import TopBar from '@/components/TopBar';
import LeftSidebar from '@/components/LeftSidebar';
import { Typography } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

//export const metadata: Metadata = {
//  title: "Task Manager",
//  description: "Generated by create next app",
//};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <html lang="en">
      <body className={inter.className} style={{ margin: '0px' }}>
        <TopBar
          onMenuClick={() => setMenuOpen(true)}
        />
        <LeftSidebar
          open={menuOpen}
          onClose={() => setMenuOpen(false)}
        />
        <main>{children}</main>
      </body>
    </html>
  );
}
